services:
  imageserver:
    container_name: imageserver
    build:
      dockerfile: ./app/Dockerfile
    networks:
      - gateway
    volumes:
      - uploadsImages:/app/uploads


networks:
  gateway:
    external: true
    name: g-images

volumes:
  uploadsImages:
      