FROM python:3.11.2-alpine

WORKDIR /app

COPY /app/requirements.txt /app
RUN pip3 install -r requirements.txt

COPY ./app /app

EXPOSE 9705
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:9705", "app:app"]